[build-system]
requires = ["setuptools>=77.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["pyxsdata*"]

[project]
name = "pyxsdata"
description = "Modern Python XML & JSON Data Binding with Pydantic & Dataclasses support"
authors = [
    {name = "nth-bailey"},
]
maintainers = [
    {name = "nth-bailey"},
]
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Software Development :: Code Generators",
    "Topic :: Text Processing :: Markup :: XML",
]
keywords = ["xsd", "wsdl", "schema", "dtd", "binding", "xml", "json", "dataclasses", "generator", "cli", "pydantic"]
requires-python = ">=3.12"
dependencies = []
dynamic = ["version"]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.urls]
Homepage = "https://github.com/nth-bailey/pyxsdata"
Source = "https://github.com/nth-bailey/pyxsdata"
Documentation = "https://nth-bailey.github.io/pyxsdata/"
Changelog = "https://nth-bailey.github.io/pyxsdata/changelog/"

[project.optional-dependencies]
cli = [
    "click>=8.1.8",
    "jinja2>=3.1.5",
    "toposort>=1.10",
    "ruff>=0.9.8",
]
pydantic = [
    "pydantic>=2.10.0",
]
docs = [
    "zensical>=0.0.59",
]
lxml = ["lxml>=5.3.0"]
soap = ["requests>=2.32.3"]
test = [
    "pre-commit>=4.1.0",
    "pytest>=8.3.0",
    "pytest-benchmark>=5.1.0",
    "pytest-cov>=6.0.0",
]
all = [
    "pyxsdata[cli,lxml,soap,pydantic]",
]

[project.scripts]
pyxsdata = "pyxsdata.__main__:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.dynamic]
version = {attr = "pyxsdata.__version__"}

[tool.ty.environment]
python-version = "3.12"

[tool.ty.src]
exclude = ["tests/fixtures"]

[tool.ruff]
target-version = "py312"
line-length = 88

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # flake8-annotations
    "ANN",
    # flake8-comprehensions
    "C4",
    # isort
    "I",
    # pydocstyle
    "D",
    # flake-raise
    "RSE",
    # flake-return
    "RET",
    # Ruff rules
    "RUF",
    # Flake Simplify
    "SIM",
]

ignore = [
    "ANN204",
    "ANN206",
    "ANN401",
    "E203",
    "B028",
    "B904",
    "D100",
    "D104",
    "RUF009",
]

exclude = ["tests/fixtures"]

[tool.ruff.lint.per-file-ignores]
"**/{tests}/*" = ["ANN001", "ANN002", "ANN003", "E501", "B018", "D"]
"tests/formats/dataclass/cases/**" = ["UP"]
"**/utils/testing.py" = ["D"]
"docs/*" = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
line-ending = "lf"
quote-style = "double"
indent-style = "space"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--color=yes --benchmark-skip"
doctest_optionflags = "NORMALIZE_WHITESPACE"


[tool.coverage.run]
omit = [
    "pyxsdata/__main__.py",
    "pyxsdata/utils/debug.py",
]
